[package]
name = "phoxels"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.16.0"
noise = "*"
indexmap = "*"
bevy_mod_debugdump = "*"
bitflags = "*"

[profile.dev.package."*"]
opt-level = 3